version: '3.7'

services:
  backend:
    build: backend
    environment:
      APPID: ${APPID}
    ports:
      - ${API_PORT:-9000}:9000

  frontend:
    build: frontend
    environment:
      ENDPOINT: ${ENDPOINT}
    ports:
      - ${CLIENT_PORT:-8000}:8000